import { Mulish } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const mulish = Mulish({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Avid Dev Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <div className="flex flex-col h-screen bg-gradient-to-b from-sky-300 via-orange-200 to-cyan-200 overflow-y-auto">
          <div className="mt-5">
            <NavBar />
          </div>
          <div className="flex-grow ">{children}</div>
        </div>
      </body>
    </html>
  );
}
