import { Mulish } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const mulish = Mulish({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Avid Dev Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <div className="w-screen h-screen top-0 bottom-0 bg-cover overflow-y-auto bg-gradient-to-b from-sky-300 via-orange-200 to-cyan-200">
          <div className="h-24">
            <NavBar />
          </div>
          <div className="h-[calc(100vh-6rem)]">{children}</div>
        </div>
      </body>
    </html>
  );
}
